FROM golang:latest

WORKDIR /go/src/app

COPY . .

RUN apt-get update && \
    apt-get install -y iproute2 && \
    apt-get install -y iptables && \
    apt-get install -y iputils-ping && \
    apt-get install -y tcpdump && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

CMD ["go", "run", ".","api", "--network", "custom", "--beacon-uris", "http://172.23.0.6:3501", "--secret-key", "0x607a11b45a7219cc61a3d9c5fd08c7eebd602a6a19a977f8d3771d5711a550f2", "--db", "postgres://postgres:postgres@172.23.0.12:5432/postgres?sslmode=disable", "--loglevel", "trace,debug,info,warn/warning,error,fatal,panic", "--debug", "--listen-addr", "0.0.0.0:9062", "--redis-uri", "172.23.0.10:6379", "--blocksim", "http://172.23.0.7:8547"]